ARDUINO_DIR   = /usr/share/arduino
# ARDMK_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = 
USER_LIB_PATH = /home/thorai/Documents/Research/Thor IOT/iot_scripts/arduino/Main/libraries
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk